Fix bug in Marginal 1D tool & serialization
facebookresearch/beanmachine pull request #1759
Opened 2022-10-18 21:25 UTC by ndmlny-qs

### Motivation

- Fixes incorrect mean value calculation in the tool.
- Updates how serialization is performed to catch indexed random variables.

### Changes proposed

- Removes console logging from the Marginal1d tool, as it is not necessary.
- Updates how a Bean Machine model is serialized. Previously, we were not capturing higher dimensions of random variables, which can happen when a random variable has a dummy index.
- Fixes a bug where we calculated the mean of the given 1D KDE estimate of a random variable, instead of calculating the mean of the actual raw data.

### Test Plan

More tutorials were used to visually inspect the output of the tool.

- Coin flipping.
- Robust linear regression.
- Logistic regression.
- Sparse logistic regression.

### Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/facebookresearch/beanmachine/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

2022-10-19 00:39 UTC, ndmlny-qs commented
@horizon-blue I like your idea, restated here for context.

> ...we should find a way to let [the] user [index] into the dimensions [of a random variable]...

This is a great idea, and I think I can explore that in this PR. This pattern comes up in several tutorials, and should be something that the user is capable of doing. It will require a change to the UI, but the added functionality adds a lot to the UX. Especially when a model has hundreds of indexed values for a single random variable.

2022-10-19 23:57 UTC, horizon-blue commented
> This is a great idea, and I think I can explore that in this PR.

Glad to hear that you like this idea (and thanks for correcting the many grammar errors that I made :) ), though we don't necessarily have to get this done in this PR. Since this PR is about fixing a bug that impacts the usability of the tool, it's better for us to get a workable version soon. After the bug is fixed, we can then work on UX improvements freely.

2022-10-19 23:58 UTC, horizon-blue requested changes
On the tool itself, are we intend for it to support higher dimensional random variables that don't have a dimension of 1 in its shape? The reason I asked is that even with this fix, we still can't serialize, say, a random variable with size `(3,)`:

```python
>>> samples[beta()].shape  # (num_chains = 4, num_samples = 2000)
torch.Size([4, 2000, 3])

>>> print(serialize_bm(samples)["beta()"])
[]
```

Speaking of which, it would be great to have some unit tests to cover this serialization tool, so we don't have to manually test for these :)

2022-10-20 00:06 UTC, horizon-blue commented
Another thing that we should be aware of is that the `MonteCarloSamples` object has a `get_chain()` method that returns a narrower version of the `MonteCarloSamples`, where each value no longer has the leading chain dimension. With the change here we will run into error if people try to run `samples.get_chain(0).diagnostics.marginal1d()`.

Which leads me to think that it might be easier to convert a `MonteCarloSamples` object to an `arviz.InferenceData` object before serializing it, because the underlying xarray dataset has better support for indexing and slicing operators. It shouldn't require too much change here. Plus, people can convert samples from other PPL to an `InferenceData` and manually invoke the diagnostic widgets on it, if they ever want to do so.

2022-10-20 16:46 UTC, ndmlny-qs commented
I'm going to split this PR into two:

1. the bug fix for the mean calculation
2. serialization updates

I think the split will allow for more focused discussion about the serializer, and I can focus on writing tests for it in that branch.

2022-10-21 00:21 UTC, closed without merging